diri_ros:
  ubuntu: [ros-noetic-diri-ros]
flight-algorithms:
  ubuntu: [air-flight-algorithms]
flight_example:
  ubuntu: [ros-noetic-flight-example]
flight_sdk_ros:
  ubuntu: [ros-noetic-flight-sdk-ros]
libmavsdk:
  ubuntu: [libmavsdk-dev]
livox_ros_driver:
  ubuntu: [ros-noetic-livox-ros-driver]
onboardsdk:
  ubuntu: [onboardsdk]
utm:
  ubuntu: [python3-utm]
gmplot:
  ubuntu: [python3-gmplot]
simplekml:
  ubuntu: [python3-simplekml]
flight-sdk:
  ubuntu: [python3-flight-sdk]
