air-flight-algorithms:
  ubuntu: [air-flight-algorithms]
diri_ros:
  ubuntu: [ros-noetic-diri-ros]
flight-algorithms:
  ubuntu: [air-flight-algorithms]
flight_example:
  ubuntu: [ros-noetic-flight-example]
flight_falcker_tanks:
  ubuntu: [ros-noetic-flight-falcker-tanks]
flight_fence_perimeter:
  ubuntu: [ros-noetic-flight-fence-perimeter]
flight_feature:
  ubuntu: [ros-noetic-flight-feature]
flight_image_logger:
  ubuntu: [ros-noetic-flight-image-logger]
flight_manual:
  ubuntu: [ros-noetic-flight-manual]
flight_sdk_ros:
  ubuntu: [ros-noetic-flight-sdk-ros]
flight_sdk_ros_msgs:
  ubuntu: [ros-noetic-flight-sdk-ros-msgs]
flight_wind_turbine:
  ubuntu: [ros-noetic-flight-wind-turbine]
flight_simple_sim:
  ubuntu: [ros-noetic-flight-simple-sim]
gmplot:
  ubuntu: [python3-gmplot]
libmavsdk:
  ubuntu: [libmavsdk-dev]
livox_ros_driver:
  ubuntu: [ros-noetic-livox-ros-driver]
onboardsdk:
  ubuntu: [onboardsdk]
payloadsdk:
  ubuntu: [payloadsdk]
python3-pymap3d:
  ubuntu:
    '*': [python3-pymap3d]
python3-arrow:
  ubuntu: [python3-arrow]
simplekml:
  ubuntu: [python3-simplekml]
utm:
  ubuntu: [python3-utm]
airsim:
  ubuntu:
    pip:
      packages: [airsim]
