diri_ros:
  ubuntu: [ros-noetic-diri-ros]
flight-algorithms:
  ubuntu: [air-flight-algorithms]
flight_example:
  ubuntu: [ros-noetic-flight-example]
flight_falcker_tanks:
  ubuntu: [ros-noetic-flight-falcker-tanks]
flight_feature:
  ubuntu: [ros-noetic-flight-feature]
flight_manual:
  ubuntu: [ros-noetic-flight-manual]
flight_sdk_ros:
  ubuntu: [ros-noetic-flight-sdk-ros]
flight_sdk_ros_msgs:
  ubuntu: [ros-noetic-flight-sdk-ros-msgs]
gmplot:
  ubuntu: [python3-gmplot]
libmavsdk:
  ubuntu: [libmavsdk-dev]
livox_ros_driver:
  ubuntu: [ros-noetic-livox-ros-driver]
onboardsdk:
  ubuntu: [onboardsdk]
simplekml:
  ubuntu: [python3-simplekml]
utm:
  ubuntu: [python3-utm]
