diri_ros:
  ubuntu: [ros-noetic-diri-ros]
flight-algorithms:
  ubuntu: [air-flight-algorithms]
flight_example:
  ubuntu: [ros-noetic-flight-example]
flight_sdk_ros:
  ubuntu: [ros-noetic-flight-sdk-ros]
libmavsdk:
  ubuntu: [libmavsdk-dev]
onboardsdk:
  ubuntu: [onboardsdk]
